rails-multiuser-authentication/config/routes.rb
Gamez::Application.routes.draw do

  resources :user_sessions, :only => [:new, :create, :destroy]

  match '/login' => 'user_sessions#new', :as => :login
  match '/logout' => 'user_sessions#destroy', :as => :logout

  root :to => 'user_sessions#new'

  namespace :admin do
    resources :users
    resources :roles
    root :controller => 'admin', :action => 'index'
  end

  namespace :members do
    resources :games
    resources :users
    match '/profile', :controller => 'users', :action => 'show', 
      :as => :profile
    match '/profile/edit', :controller => 'users', :action => 'edit',
      :as => :edit_profile
    match '/profile/:id', :controller => 'users', :action => 'update',
      :as => :update_profile
    root :controller => 'games', :action => 'index'
  end
  
end

rails-multiuser-authentication/app/models/role.rb
class Role < ActiveRecord::Base
  has_many :assignments
  has_many :users, :through => :assignments

  validates_presence_of :name
end

rails-multiuser-authentication/app/controllers/admin/roles_controller.rb
class Admin::RolesController < Admin::AdminController
  before_filter :require_user
  
  def index
    @roles = Role.all
  end

  def show
    @role = Role.find(params[:id], :include => :users)
  end

  def create
    @role = Role.new(params[:role])

    if @role.save
      respond_to do |format|
        format.html { redirect_to admin_roles_path, 
          :notice => "Role was sucessfully created."}
      end
    else
      respond_to do |format|
        format.html { redirect_to new_admin_role_path,
          :error => "Role could not be created." }
      end
    end
  end

  def edit
    @role = Role.find(params[:id])
  end

  def update
    @role = Role.find(params[:id])

    respond_to do |format|
      if @role.update_attributes(params[:role])
        format.html { redirect_to admin_roles_path, 
          notice: "Role was sucessfully updated."}
      else
        format.html { render :action => "edit" }
      end
    end
  end

end

rails-multiuser-authentication/app/helpers/admin/roles_helper.rb
module Admin::RolesHelper

  def role_actions(role)
    @role = role
    render "actions"
  end

  def view_role(role)
    link_to image_tag('magnifier.png'), admin_role_path(role), :title => 'View role'
  end

  def edit_role(role)
    link_to image_tag('page_edit.png'), edit_admin_role_path(role), 
      :title => 'Edit role'
  end

  def delete_role(role)
    link_to image_tag('bin.png'), admin_role_path(role), confirm: 'Are you sure?', 
      :method => :delete, :title => 'Delete role'
  end

end

rails-multiuser-authentication/app/views/admin/roles/_actions.html.haml
%ul.role_actions
  %li= view_role(@role)
  %li= edit_role(@role)
  %li= delete_role(@role)

rails-multiuser-authentication/app/views/admin/roles/_role.html.haml
%h2= "Editing the #{@role.name} role"
%ul.role_form
  = form_for @role, :url => :admin_role do |f|
    %li= f.label :description
    %li= f.text_area :description, :size => "25x10"
    %li= f.submit "Submit"

rails-multiuser-authentication/app/views/admin/roles/create.html.haml
%h1 Admin::Roles#create
%p Find me in app/views/admin/roles/create.html.haml

rails-multiuser-authentication/app/views/admin/roles/destroy.html.haml
%h1 Admin::Roles#destroy
%p Find me in app/views/admin/roles/destroy.html.haml

rails-multiuser-authentication/app/views/admin/roles/edit.html.haml
= render :partial => 'admin/roles/role', :object => @role

rails-multiuser-authentication/app/views/admin/roles/index.html.haml
%table.roles_table{ :cellspacing => "0" }
  %thead
    %tr.roles_table_header
      %th Role
      %th Description
      %th # of Users
  %tbody
    - @roles.each do |role|
      %tr
        %td= link_to role.name, admin_role_path(role)
        %td= role.description
        %td

rails-multiuser-authentication/app/views/admin/roles/show.html.haml
%h2= @role.name
.description= @role.description

%span= link_to "Edit", edit_admin_role_path(@role), :class => 'button'

%h3= "List of #{@role.name.pluralize}"
%table.users_table
  %thead
    %tr
      %th Name
      %th Username
      %th Email
      %th Last Login
      %th Games
  %tbody
    - @role.users.each do |user|
      %td= link_to user.full_name, admin_user_path(user)
      %td= user.username
      %td= user.email
      %td= user.last_login(Time.now)
      %td

rails-multiuser-authentication/app/views/admin/roles/update.html.haml
%h1 Admin::Roles#update
%p Find me in app/views/admin/roles/update.html.haml